---
driver:
  name: docker
driver_config:
  http_proxy: <%= ENV.fetch('HTTP_PROXY', "http://172.17.42.1:3128") %>
  https_proxy: <%= ENV.fetch('HTTPS_PROXY', "http://172.17.42.1:3128") %>
  instance_name: denny-elk
  use_sudo: false
  privileged: true
  tls_verify: true
  tls_cacert: /Users/mac/Dropbox/private_data/project/docker/docker_tls_oscgc/ca.pem
  tls_cert: /Users/mac/Dropbox/private_data/project/docker/docker_tls_oscgc/cert.pem
  tls_key: /Users/mac/Dropbox/private_data/project/docker/docker_tls_oscgc/key.pem
  socket: tcp://192.168.1.185:4243
  provision_command: "curl -L https://raw.githubusercontent.com/DennyZhang/data/master/denny_chef_provision.sh | bash -e"

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - recipe[apt::default]
      - recipe[elk::default]
    attributes:
