---
driver:
  name: vagrant
  network:
  - ["forwarded_port", {guest: 5601, host: 5601}]
  - ["forwarded_port", {guest: 80, host: 8080}]
  - ["forwarded_port", {guest: 9200, host: 9200}]
  - ["private_network", {ip: "192.168.33.33"}]

provisioner:
  name: chef_solo

platforms:
  - name: ubuntu-14.04
#  - name: centos-7.2

suites:
  - name: default
    run_list:
      - recipe[elk::default]
    attributes:
