---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  roles_path: ../../roles
  environments_path: ../../environments/
  client_rb:
    environment: example

verifier:
  name: inspec

platforms:
  - name: ubuntu-14.04

suites:
  - name: default
    run_list:
      - role[example]
#      - recipe[c::default]
    verifier:
      inspec_tests:
        - test/recipes
    attributes:
