---
driver:
  name: vagrant

provisioner:
  name: chef_zero

platforms:
  - name: ubuntu-14.04
    run_list:
    - recipe[apt]
  - name: centos-6.8
    run_list:
    - recipe[yum]
  - name: centos-7.2
    run_list:
    - recipe[yum]
  - name: windows-2012R2
    driver:
      box: mwrock/Windows2012R2
      guest: windows
      communicator: winrm
      gui: false


suites:
  - name: default
    require_chef_omnibus: 12.14.60
    run_list:
      - recipe[filebeat::default]
    attributes:
      filebeat:
        prospectors:
          system_logs:
            filebeat:
              prospectors:
              - paths:
                - /var/log/messages
                - /var/log/syslog
                type: log
                fields:
                  type: system_logs
              - paths:
                - /var/log/*.log
                type: log
                fields:
                  type: undefined
                exclude_files:
                - /var/log/messages
                - /var/log/syslog
        config:
          output:
            elasticsearch:
              hosts: ["127.0.0.1:9200"]

  - name: runit
    require_chef_omnibus: 12.14.60
    excludes:
      - windows-2012R2 
    run_list:
      - recipe[filebeat::default]
    attributes:
      filebeat:
        service:
          init_style: 'runit'
        prospectors:
          system_logs:
            filebeat:
              prospectors:
              - paths:
                - /var/log/messages
                - /var/log/syslog
                type: log
                fields:
                  type: system_logs
              - paths:
                - /var/log/*.log
                type: log
                fields:
                  type: undefined
                exclude_files:
                - /var/log/messages
                - /var/log/syslog
        config:
          output:
            elasticsearch:
              hosts: ["127.0.0.1:9200"]
